baseURL = "https://belaunzaran.com/"
languageCode = "en-us"
title = "Luca Belaunzar√°n"
theme = "terminal"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 6
  fullWidthTheme = false
  centerTheme = true

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 2

[[menu.main]]
  name = "Skills"
  url = "/skills"
  weight = 3

[[menu.main]]
  name = "Education"
  url = "/education"
  weight = 4

[[menu.main]]
  name = "Languages"
  url = "/languages"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
