baseURL = "https://belaunzaran.com/"
languageCode = "en-us"
title = "Luca Belaunzarán - Aerospace Engineer"
theme = "terminal"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 7
  fullWidthTheme = false
  centerTheme = true
  Subtitle = "Luca Belaunzarán - Aerospace Engineering student at UNAM specializing in aeroservoelasticity and morphic wings."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1


[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 2

[[menu.main]]
  name = "Skills"
  url = "/skills"
  weight = 3

[[menu.main]]
  name = "Education"
  url = "/education"
  weight = 4

[[menu.main]]
  name = "Languages"
  url = "/languages"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 6

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.Logo]
  logoText = "Luca Belaunzarán"
  logoHomeLink = "/"
